import { execFile } from "node:child_process";
import { generateKeyPairSync, randomBytes } from "node:crypto";
import { existsSync } from "node:fs";
import { networkInterfaces } from "node:os";
import { join } from "node:path";

/**
 * Nexus's own private network, built on WireGuard (open source, no account, no company in the
 * middle). This computer is the hub: each phone or laptop gets its own keys and can reach only
 * this computer's private address — never the rest of the home or office network.
 */

export const TUNNEL_NAME = "nexus";
export const DEFAULT_WIREGUARD_PORT = 51820;

export interface WireGuardKeys {
  privateKey: string;
  publicKey: string;
}

/** A Curve25519 key pair in WireGuard's base64 format (generated locally, no wg.exe needed). */
export function wireguardKeys(): WireGuardKeys {
  const { privateKey, publicKey } = generateKeyPairSync("x25519");
  const d = privateKey.export({ format: "jwk" }).d!;
  const x = publicKey.export({ format: "jwk" }).x!;
  const b64 = (u: string) => Buffer.from(u, "base64url").toString("base64");
  return { privateKey: b64(d), publicKey: b64(x) };
}

/** An extra shared secret per device (post-quantum hardening, as WireGuard recommends). */
export const presharedKey = () => randomBytes(32).toString("base64");

const KEY = /^[A-Za-z0-9+/]{42}[AEIMQUYcgkosw048]=$/;
const key = (k: string) => {
  if (!KEY.test(k)) throw new Error("Invalid WireGuard key.");
  return k;
};

// ------------------------------------------------------------------ addresses

export interface Subnet {
  /** e.g. "10.73.0" — the network is <base>.0/24, this computer is <base>.1. */
  base: string;
}

export const subnetCidr = (s: Subnet) => `${s.base}.0/24`;
export const serverAddress = (s: Subnet) => `${s.base}.1`;

const CANDIDATES = ["10.73.0", "10.173.73", "172.29.73", "192.168.237"];

/** A /24 that doesn't clash with any network this computer is already on. */
export function pickSubnet(inUse: string[] = localIPv4s()): Subnet {
  const taken = new Set(inUse.map((ip) => ip.split(".").slice(0, 3).join(".")));
  const base = CANDIDATES.find((c) => !taken.has(c));
  if (!base) throw new Error("No free private address range was found.");
  return { base };
}

function localIPv4s(): string[] {
  return Object.values(networkInterfaces())
    .flat()
    .filter((n): n is NonNullable<typeof n> => !!n && n.family === "IPv4" && !n.internal)
    .map((n) => n.address);
}

/** The next free device address (.2 – .254). */
export function nextDeviceAddress(subnet: Subnet, used: string[]): string {
  for (let i = 2; i < 255; i++) {
    const a = `${subnet.base}.${i}`;
    if (!used.includes(a)) return a;
  }
  throw new Error("The private network is full (253 devices).");
}

// ------------------------------------------------------------------ configuration files

export interface WireGuardDevice {
  id: string;
  name: string;
  address: string;
  publicKey: string;
  presharedKey: string;
}

export interface WireGuardServer {
  subnet: Subnet;
  port: number;
  privateKey: string;
  devices: WireGuardDevice[];
}

const safeName = (s: string) => s.replace(/[\r\n#]/g, " ").slice(0, 60);

/** The tunnel configuration for this computer (what the WireGuard service runs). */
export function renderServerConfig(s: WireGuardServer): string {
  const lines = ["# Generated by Nexus — changes are made in Nexus and applied automatically.", "[Interface]", `PrivateKey = ${key(s.privateKey)}`, `ListenPort = ${s.port}`, `Address = ${serverAddress(s.subnet)}/24`, ""];
  for (const d of s.devices) {
    lines.push(`# ${safeName(d.name)}`, "[Peer]", `PublicKey = ${key(d.publicKey)}`, `PresharedKey = ${key(d.presharedKey)}`, `AllowedIPs = ${d.address}/32`, "");
  }
  return lines.join("\r\n");
}

/**
 * The file (or QR code) for one phone or laptop. It sends only traffic for this computer's private
 * address through the tunnel, so the device's normal internet use is unaffected.
 */
export function renderDeviceConfig(o: { device: WireGuardDevice; devicePrivateKey: string; serverPublicKey: string; subnet: Subnet; endpoint: string }): string {
  if (!/^[A-Za-z0-9.:[\]-]+:\d{1,5}$/.test(o.endpoint)) throw new Error("Invalid endpoint.");
  return [
    "[Interface]",
    `PrivateKey = ${key(o.devicePrivateKey)}`,
    `Address = ${o.device.address}/32`,
    "",
    "[Peer]",
    `PublicKey = ${key(o.serverPublicKey)}`,
    `PresharedKey = ${key(o.device.presharedKey)}`,
    `AllowedIPs = ${serverAddress(o.subnet)}/32`,
    `Endpoint = ${o.endpoint}`,
    // Keeps the connection open through home routers and mobile networks.
    "PersistentKeepalive = 25",
    "",
  ].join("\n");
}

// ------------------------------------------------------------------ the WireGuard program

export interface WireGuardProgram {
  wireguard: string;
  wg: string;
}

/**
 * The official WireGuard for Windows app. Only Program Files is used: the service runs as SYSTEM
 * and must never start a program from a folder a normal account can change.
 */
export function locateWireGuard(programFiles = process.env.ProgramFiles ?? "C:\\Program Files"): WireGuardProgram | null {
  const dir = join(programFiles, "WireGuard");
  const p = { wireguard: join(dir, "wireguard.exe"), wg: join(dir, "wg.exe") };
  return existsSync(p.wireguard) && existsSync(p.wg) ? p : null;
}

export interface PeerStatus {
  publicKey: string;
  endpoint: string | null;
  /** Last successful handshake, or null if the device never connected. */
  lastHandshake: Date | null;
  receivedBytes: number;
  sentBytes: number;
}

/** Parses `wg show <tunnel> dump` (the first line describes this computer). */
export function parseWgDump(out: string): PeerStatus[] {
  return out
    .trim()
    .split(/\r?\n/)
    .slice(1)
    .map((l) => l.split("\t"))
    .filter((f) => f.length >= 8)
    .map((f) => ({
      publicKey: f[0]!,
      endpoint: f[2] && f[2] !== "(none)" ? f[2] : null,
      lastHandshake: Number(f[4]) > 0 ? new Date(Number(f[4]) * 1000) : null,
      receivedBytes: Number(f[5]) || 0,
      sentBytes: Number(f[6]) || 0,
    }));
}

export type Exec = (file: string, args: string[]) => Promise<{ code: number; out: string }>;
export const defaultExec: Exec = (file, args) =>
  new Promise((resolve) =>
    execFile(file, args, { windowsHide: true, timeout: 60_000 }, (err, stdout, stderr) =>
      resolve({ code: err ? (typeof err.code === "number" ? err.code : 1) : 0, out: `${stdout}${stderr}` }),
    ),
  );

/** Installs, updates and removes the Windows service that runs the tunnel. */
export class WireGuardTunnel {
  constructor(
    private readonly program: WireGuardProgram,
    private readonly exec: Exec = defaultExec,
  ) {}

  /** Windows service name the WireGuard app uses for a tunnel. */
  static serviceName = `WireGuardTunnel$${TUNNEL_NAME}`;

  async running(): Promise<boolean> {
    const r = await this.exec("sc.exe", ["query", WireGuardTunnel.serviceName]);
    return r.code === 0 && /RUNNING/.test(r.out);
  }

  /** Installs (or reinstalls) the tunnel service from a config file named nexus.conf. */
  async install(configFile: string): Promise<void> {
    if (!configFile.toLowerCase().endsWith(`${TUNNEL_NAME}.conf`)) throw new Error("The tunnel file must be called nexus.conf.");
    await this.exec(this.program.wireguard, ["/uninstalltunnelservice", TUNNEL_NAME]);
    const r = await this.exec(this.program.wireguard, ["/installtunnelservice", configFile]);
    if (r.code !== 0) throw new Error(`WireGuard couldn't start the private network: ${r.out.trim() || `exit code ${r.code}`}`);
  }

  async uninstall(): Promise<void> {
    await this.exec(this.program.wireguard, ["/uninstalltunnelservice", TUNNEL_NAME]);
  }

  async peers(): Promise<PeerStatus[]> {
    const r = await this.exec(this.program.wg, ["show", TUNNEL_NAME, "dump"]);
    return r.code === 0 ? parseWgDump(r.out) : [];
  }
}
